### ISSUE TITLE
Add sources parameter to fringe

### ISSUE THREAD

**Issue by lenafm** [datasketch/homodatum#11]
`fringe` doesn't have a `sources` parameter, it has to be passed through the `meta` parameter.

However, `dsviz` and `drop` both have a `sources` parameter that can be passed through `args` (see below example of `dsviz`). Obviously `dsviz`, `drop` and `fringe` _need_ to have some different parameters but I suggest that the ones that _can_ be the same, are accessed in the same way. 

E.g., `fringe` could have a `sources` parameter like `dsviz` and `drop`.

```
  args <- list(...)

[...]

  dv <- list(
    name = name,
    description = description,
    slug = create_slug(name),
    type = type,
    viz_type = type,
    width = 600L,
    height = 400L,
    access = args$access %||% "private",
    license = NULL,
    #time_created = NULL,
    time_last_updated = args$time_last_updated %||% unix_timestamp(),
    formats = args$formats %||% formats,
    tags = args$tags,
    sources = args$sources,
    dsapp = args$dsapp,
    fringe = args$fringe,
    viz = viz
  )
```

**Comment by jpmarindiaz** [comment]
Not necessary, everything that goes in as `...` in a fringe gets treated as `meta`

This works:
```
f <- fringe(x,
            name = "Some Name",
            sources = list(
              list(title = "Title", path = "path.com")
            ),
            this_other_thing = "Also endsup in meta"
)
```

**Comment by lenafm** [comment]
The problem with that when you save metadata for a dsviz, drop, or fringe, you have to use `meta = list(sources = list(...))` for `fringe` and `sources = list(...)` for the other two. 

Might be good if it was consistent.

**Comment by lenafm** [comment]
Ah no, you're right, it does work without specifying meta.
