### ISSUE TITLE
Error in fringe when data Gnm, Gcd, Gln or Glt

### ISSUE THREAD

**Issue by CamilaAchury** [datasketch/homodatum#7]
```
 data <- sample_data('Gnm-Num')
 f <- homodatum::fringe(data)
```
![imagen](https://user-images.githubusercontent.com/17035597/81081700-df9d2a80-8eb7-11ea-8129-2e8da02dae68.png)

**Comment by jpmarindiaz** [comment]
Fixed in hc branch with 
3626b98
